name: isolate_bloc
description: A dart package that helps implement the BLoC pattern. BLoC works in Isolate and don't slow down UI.
version: 2.1.1
homepage: https://github.com/Maksimka101/isolate-bloc/tree/master/packages/isolate_bloc
repository: https://github.com/Maksimka101/isolate-bloc/tree/master/packages/isolate_bloc

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  combine:
  equatable:
  flutter:
    sdk: flutter
  provider: 
  uuid: 

dev_dependencies:
  all_lint_rules_community:
  dart_code_metrics:
  flutter_test:
    sdk: flutter
  mocktail: 
  path: 
